### ISSUE TITLE
Provide configuration via Liferay Control Panel

### ISSUE THREAD

**Issue by zipwiz** [finalist/liferay-oidc-plugin#11]
Actually every change of the plugin configuration including switching the plugin on/off requires re-reading portal-ext.properties, which in turn requires restart of Liferay.

It would be extremely useful to have this plugin configurable via Liferay Control Panel with immediate result.

This would require a Liferay JSP hook for Control Panel and some further management code.

**Comment by gvanderploeg** [comment]
Thanks for this suggestion. Indeed a good idea. Probably not with a JSP hook but a proper Control Panel Portlet, but that's a detail.

**Comment by gvanderploeg** [comment]
About to work on this, together with #12...

**Comment by zipwiz** [comment]
... and LR62? (I know that LR62 is quite like a zombie ... but due to certain license politics it is still in use on many sites ...)

**Comment by gvanderploeg** [comment]
Due to the fact that both the configuration backend and the portlet-setup is different between 6.2 and 7.0, it would be a complete duplicate implementation between the two. This holds me from implementing the 6.2 control panel configuration.
Maybe at some point in the future, but for now I accept that 6.2 users have a sub-optimal experience... (but you're free to convince me anyway :-) )

**Comment by zipwiz** [comment]
It was just a kind of hope :-/ Actually I do not think that I will find time to do it by myself however.
